import turtle
def drawSix(forward):
    turtle.seth(30)
    turtle.fd(forward)
    turtle.seth(270)
    turtle.fd(forward)
    turtle.seth(150)
    turtle.fd(forward)
    turtle.penup()
    turtle.seth(30)
    turtle.fd(forward * 2/3)
    turtle.seth(-30)
    turtle.fd(forward * 2/3)
    turtle.pendown()
    turtle.seth(210)
    turtle.fd(forward)
    turtle.seth(90)
    turtle.fd(forward)
    turtle.seth(-30)
    turtle.fd(forward)
turtle.setup(650, 350, None, None)
turtle.penup()
turtle.fd(-50)
turtle.pendown()
turtle.pensize(10)
turtle.pencolor("red")
drawSix(99)
turtle.done()