import turtle
turtle.pensize(2)
turtle.color('blue')
turtle.circle(10)
turtle.color('yellow')
turtle.circle(40)
turtle.color('grey')
turtle.circle(80)
turtle.color('red')
turtle.circle(160)
turtle.color('white')
turtle.circle(320)
turtle.color('black')
turtle.circle(640)
